name: Wpr003n-Openwrt15-CC-diy
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt-get install build-essential asciidoc binutils bzip2 gawk gettext git subversion libssl-dev libncurses5-dev patch unzip zlib1g-dev libc6-dev libbz2-dev gdisk flex
    - name: Clone source code
      run: |
        git clone https://github.com/syb999/openwrt-15.05
        ls
        cd openwrt
